version: '3'

services:

  task5:
    container_name: task5-docker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - redis
  redis: 
    container_name: redis-docker
    image: redis  
    restart: unless-stopped
    ports:
      - 6300:6379